In [1]:
import pandas as pd  

var = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})

print(var)

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [7]:
var["C"]=var["A"]+var["B"]
print(var)

   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

In [11]:
var1 = pd.DataFrame({"A":[10,20,30,40],"B":[15,16,17,18]})
var1

    A   B
0  10  15
1  20  16
2  30  17
3  40  18

In [14]:
var1["python"] = var1["A"] <= 20
var1["python_1"] = var1["B"] >= 16
var1

    A   B  python  python_1
0  10  15    True     False
1  20  16    True      True
2  30  17   False      True
3  40  18   False      True