In [2]:
# REPLACE

import pandas as pd  

var = pd.read_csv("C:\\Users\\param\\OneDrive\\Desktop\\pandas\\Test_new.csv")

var

   Unnamed: 0  a  s  d
0           0  1  1  1
1           1  2  2  2
2           2  3  3  3
3           3  4  4  4
4           4  5  5  5
5           5  6  6  6

In [5]:
# var.replace(to_replace=1,value=22)

var.replace(to_replace=2,value="aman")

  Unnamed: 0     a     s     d
0          0     1     1     1
1          1  aman  aman  aman
2       aman     3     3     3
3          3     4     4     4
4          4     5     5     5
5          5     6     6     6

In [11]:
var.replace(1,method="ffill",limit=3)

C:\Users\param\AppData\Local\Temp\ipykernel_15744\271419978.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  var.replace(1,method="ffill",limit=3)

   Unnamed: 0  a  s  d
0           0  1  1  1
1           0  2  2  2
2           2  3  3  3
3           3  4  4  4
4           4  5  5  5
5           5  6  6  6

In [13]:
var.replace(1,method="ffill",limit=3,inplace=True)

var

C:\Users\param\AppData\Local\Temp\ipykernel_15744\4193017942.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  var.replace(1,method="ffill",limit=3,inplace=True)

   Unnamed: 0  a  s  d
0           0  1  1  1
1           0  2  2  2
2           2  3  3  3
3           3  4  4  4
4           4  5  5  5
5           5  6  6  6

In [15]:
# INTERPOLATE

import pandas as pd 

var = pd.read_csv("C:\\Users\\param\\OneDrive\\Desktop\\pandas\\Test_new.csv")

var

   Unnamed: 0  a  s  d
0           0  1  1  1
1           1  2  2  2
2           2  3  3  3
3           3  4  4  4
4           4  5  5  5
5           5  6  6  6

In [ ]:
var.interpolate(method="linear",axis=0)               # always use and work for number data

   Unnamed: 0  a  s  d
0           0  1  1  1
1           1  2  2  2
2           2  3  3  3
3           3  4  4  4
4           4  5  5  5
5           5  6  6  6