In [4]:
import pandas as pd  

var = pd.read_csv("C:\\Users\\param\\OneDrive\\Desktop\\pandas\\Test_new1.csv")

var

   a    s    d
0  1  1.0  1.0
1  2  NaN  2.0
2  3  3.0  NaN
3  4  4.0  4.0
4  5  5.0  5.0
5  6  6.0  6.0

In [9]:
# var.dropna()

# var.dropna(axis=1)    # for column drop

# var.dropna(how = "any")   # full blank row delete

var.dropna(how = "all")    # all tab hii work krega jab full row blank hogi

   a    s    d
0  1  1.0  1.0
1  2  NaN  2.0
2  3  3.0  NaN
3  4  4.0  4.0
4  5  5.0  5.0
5  6  6.0  6.0

In [11]:
var.dropna(subset=["d"])

   a    s    d
0  1  1.0  1.0
1  2  NaN  2.0
3  4  4.0  4.0
4  5  5.0  5.0
5  6  6.0  6.0

In [ ]:
# var.dropna(inplace=True)
# var
var.dropna(thresh = 2)

   a    s    d
0  1  1.0  1.0
3  4  4.0  4.0
4  5  5.0  5.0
5  6  6.0  6.0