In [21]:
import pandas as pd 

var1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var2 = pd.DataFrame({"A":[1,2,3,4],"B":[21,22,23,24]})

# pd.merge(var1,var2,on="A")

# pd.merge(var1,var2,how="outer",indicator=True)  

# pd.merge(var1,var2,left_index=True,right_index=True)

pd.merge(var1,var2,left_index=True,right_index=True,suffixes=("name","id"))

   Aname  Bname  Aid  Bid
0      1     11    1   21
1      2     12    2   22
2      3     13    3   23
3      4     14    4   24

In [27]:
#CONCAT

sr1 = pd.Series([1,2,3,4])
sr2 = pd.Series([11,21,31,41])


pd.concat([sr1,sr2])

0     1
1     2
2     3
3     4
0    11
1    21
2    31
3    41
dtype: int64

In [30]:
d1 = pd.Series([1,2,3,4])
d2 = pd.Series([11,21,31,41])

pd.concat([d1,d2],axis=1)

   0   1
0  1  11
1  2  21
2  3  31
3  4  41

In [35]:
d1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
d2 = pd.DataFrame({"A":[1,2,3,4],"C":[21,22,23,24]})

pd.concat([d1,d2],axis=1,keys=["d1","d2"])

  d1     d2
   A   B  A   C
0  1  11  1  21
1  2  12  2  22
2  3  13  3  23
3  4  14  4  24