In [3]:
import pandas as pd  

csv_1 = pd.read_csv("C:\\Users\\param\\Downloads\\Orders.csv")

csv_1

    Order ID  Order Date CustomerName             State     City
0    B-26055  10-03-2018    Harivansh     Uttar Pradesh  Mathura
1    B-25993  03-02-2018       Madhav             Delhi    Delhi
2    B-25973  24-01-2018  Madan Mohan     Uttar Pradesh  Mathura
3    B-25923  27-12-2018        Gopal       Maharashtra   Mumbai
4    B-25757  21-08-2018     Vishakha    Madhya Pradesh   Indore
..       ...         ...          ...               ...      ...
495  B-25742  03-08-2018       Ashwin               Goa      Goa
496  B-26088  26-03-2018       Bhavna            Sikkim  Gangtok
497  B-25707  01-07-2018      Shivani       Maharashtra   Mumbai
498  B-25758  22-08-2018      Shubham  Himachal Pradesh    Simla
499  B-26095  28-03-2018      Monisha         Rajasthan   Jaipur

[500 rows x 5 columns]

In [4]:
csv_1.index

RangeIndex(start=0, stop=500, step=1)

In [5]:
csv_1.columns

Index(['Order ID', 'Order Date', 'CustomerName', 'State', 'City'], dtype='object')

In [6]:
csv_1.describe()

       Order ID  Order Date CustomerName        State    City
count       500         500          500          500     500
unique      500         307          336           19      25
top     B-26095  24-11-2018       Shreya  Maharashtra  Indore
freq          1           7            6           94      71

In [8]:
csv_1.head(2)

  Order ID  Order Date CustomerName          State     City
0  B-26055  10-03-2018    Harivansh  Uttar Pradesh  Mathura
1  B-25993  03-02-2018       Madhav          Delhi    Delhi

In [10]:
csv_1.tail(2)

    Order ID  Order Date CustomerName             State    City
498  B-25758  22-08-2018      Shubham  Himachal Pradesh   Simla
499  B-26095  28-03-2018      Monisha         Rajasthan  Jaipur

In [14]:
# csv_1[:5]

csv_1[6:10]

  Order ID  Order Date CustomerName           State       City
6  B-25955  16-01-2018        Shiva     Maharashtra       Pune
7  B-26093  27-03-2018       Sarita     Maharashtra       Pune
8  B-25798  01-10-2018       Shishu  Andhra Pradesh  Hyderabad
9  B-25602  01-04-2018       Vrinda     Maharashtra       Pune

In [16]:
print(type(csv_1))

<class 'pandas.core.frame.DataFrame'>

In [18]:
csv_1.index.array

<NumpyExtensionArray>
[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
 ...
 490, 491, 492, 493, 494, 495, 496, 497, 498, 499]
Length: 500, dtype: int64

In [20]:
csv_1.to_numpy()

array([['B-26055', '10-03-2018', 'Harivansh', 'Uttar Pradesh', 'Mathura'],
       ['B-25993', '03-02-2018', 'Madhav', 'Delhi', 'Delhi'],
       ['B-25973', '24-01-2018', 'Madan Mohan', 'Uttar Pradesh',
        'Mathura'],
       ...,
       ['B-25707', '01-07-2018', 'Shivani', 'Maharashtra', 'Mumbai'],
       ['B-25758', '22-08-2018', 'Shubham', 'Himachal Pradesh', 'Simla'],
       ['B-26095', '28-03-2018', 'Monisha', 'Rajasthan', 'Jaipur']],
      shape=(500, 5), dtype=object)

In [22]:
import numpy as np
v = np.asarray(csv_1)
v

array([['B-26055', '10-03-2018', 'Harivansh', 'Uttar Pradesh', 'Mathura'],
       ['B-25993', '03-02-2018', 'Madhav', 'Delhi', 'Delhi'],
       ['B-25973', '24-01-2018', 'Madan Mohan', 'Uttar Pradesh',
        'Mathura'],
       ...,
       ['B-25707', '01-07-2018', 'Shivani', 'Maharashtra', 'Mumbai'],
       ['B-25758', '22-08-2018', 'Shubham', 'Himachal Pradesh', 'Simla'],
       ['B-26095', '28-03-2018', 'Monisha', 'Rajasthan', 'Jaipur']],
      shape=(500, 5), dtype=object)

In [27]:
csv_1.sort_index(axis=0,ascending = False)

    Order ID  Order Date CustomerName             State     City
499  B-26095  28-03-2018      Monisha         Rajasthan   Jaipur
498  B-25758  22-08-2018      Shubham  Himachal Pradesh    Simla
497  B-25707  01-07-2018      Shivani       Maharashtra   Mumbai
496  B-26088  26-03-2018       Bhavna            Sikkim  Gangtok
495  B-25742  03-08-2018       Ashwin               Goa      Goa
..       ...         ...          ...               ...      ...
4    B-25757  21-08-2018     Vishakha    Madhya Pradesh   Indore
3    B-25923  27-12-2018        Gopal       Maharashtra   Mumbai
2    B-25973  24-01-2018  Madan Mohan     Uttar Pradesh  Mathura
1    B-25993  03-02-2018       Madhav             Delhi    Delhi
0    B-26055  10-03-2018    Harivansh     Uttar Pradesh  Mathura

[500 rows x 5 columns]

In [29]:
csv_1["CustomerName"][0]="python"
csv_1

C:\Users\param\AppData\Local\Temp\ipykernel_14292\705298668.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  csv_1["CustomerName"][0]="python"

    Order ID  Order Date CustomerName             State     City
0    B-26055  10-03-2018       python     Uttar Pradesh  Mathura
1    B-25993  03-02-2018       Madhav             Delhi    Delhi
2    B-25973  24-01-2018  Madan Mohan     Uttar Pradesh  Mathura
3    B-25923  27-12-2018        Gopal       Maharashtra   Mumbai
4    B-25757  21-08-2018     Vishakha    Madhya Pradesh   Indore
..       ...         ...          ...               ...      ...
495  B-25742  03-08-2018       Ashwin               Goa      Goa
496  B-26088  26-03-2018       Bhavna            Sikkim  Gangtok
497  B-25707  01-07-2018      Shivani       Maharashtra   Mumbai
498  B-25758  22-08-2018      Shubham  Himachal Pradesh    Simla
499  B-26095  28-03-2018      Monisha         Rajasthan   Jaipur

[500 rows x 5 columns]

In [31]:
csv_1.loc[0,"Order ID"] = "python"
csv_1

    Order ID  Order Date CustomerName             State     City
0     python  10-03-2018       python     Uttar Pradesh  Mathura
1    B-25993  03-02-2018       Madhav             Delhi    Delhi
2    B-25973  24-01-2018  Madan Mohan     Uttar Pradesh  Mathura
3    B-25923  27-12-2018        Gopal       Maharashtra   Mumbai
4    B-25757  21-08-2018     Vishakha    Madhya Pradesh   Indore
..       ...         ...          ...               ...      ...
495  B-25742  03-08-2018       Ashwin               Goa      Goa
496  B-26088  26-03-2018       Bhavna            Sikkim  Gangtok
497  B-25707  01-07-2018      Shivani       Maharashtra   Mumbai
498  B-25758  22-08-2018      Shubham  Himachal Pradesh    Simla
499  B-26095  28-03-2018      Monisha         Rajasthan   Jaipur

[500 rows x 5 columns]

In [33]:
csv_1.loc[[2,3],["Order ID","CustomerName"]]

  Order ID CustomerName
2  B-25973  Madan Mohan
3  B-25923        Gopal

In [35]:
csv_1.iloc[0,3]

'Uttar Pradesh'

In [ ]:
# csv_1.drop("City",axis=1)   #for column

csv_1.drop(0,axis=0)       # for row

    Order ID  Order Date CustomerName             State       City
1    B-25993  03-02-2018       Madhav             Delhi      Delhi
2    B-25973  24-01-2018  Madan Mohan     Uttar Pradesh    Mathura
3    B-25923  27-12-2018        Gopal       Maharashtra     Mumbai
4    B-25757  21-08-2018     Vishakha    Madhya Pradesh     Indore
5    B-25967  21-01-2018       Sudevi     Uttar Pradesh  Prayagraj
..       ...         ...          ...               ...        ...
495  B-25742  03-08-2018       Ashwin               Goa        Goa
496  B-26088  26-03-2018       Bhavna            Sikkim    Gangtok
497  B-25707  01-07-2018      Shivani       Maharashtra     Mumbai
498  B-25758  22-08-2018      Shubham  Himachal Pradesh      Simla
499  B-26095  28-03-2018      Monisha         Rajasthan     Jaipur

[499 rows x 5 columns]